# Generated by Django 5.1.6 on 2025-04-12 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='video_url',
            new_name='material_url',
        ),
    ]
