# Generated by Django 5.1.6 on 2025-03-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_price_alter_course_students_and_more'),
        ('users', '0002_user_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(related_name='enrolled_students', to='courses.course'),
        ),
    ]
